[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:apache]
command=apachectl -D FOREGROUND
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:mysql]
command=mysqld
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
